### ISSUE TITLE
IntelliJ plugin crashed

### ISSUE THREAD

**Issue by odisseus** [VirtusLab/contextbuddy#8]
Context Buddy version 0.2.1-M2, IntelliJ version 192.7142.36
## Stack trace
```
java.lang.AssertionError: assertion failed
	at scala.Predef$.assert(Predef.scala:204)
	at org.jetbrains.plugins.scala.lang.psi.stubs.impl.PsiOwner.updateAndGetNewValue$1(PsiOwner.scala:29)
	at org.jetbrains.plugins.scala.lang.psi.stubs.impl.PsiOwner.getFromReferenceWithFilter(PsiOwner.scala:40)
	at org.jetbrains.plugins.scala.lang.psi.stubs.impl.PsiOwner.getFromReferenceWithFilter$(PsiOwner.scala:22)
	at org.jetbrains.plugins.scala.lang.psi.stubs.impl.ScTypeAliasStubImpl.getFromReferenceWithFilter(ScTypeAliasStubImpl.scala:15)
	at org.jetbrains.plugins.scala.lang.psi.stubs.impl.PsiOwner.getFromOptionalReference(PsiOwner.scala:15)
	at org.jetbrains.plugins.scala.lang.psi.stubs.impl.PsiOwner.getFromOptionalReference$(PsiOwner.scala:12)
	at org.jetbrains.plugins.scala.lang.psi.stubs.impl.ScTypeAliasStubImpl.getFromOptionalReference(ScTypeAliasStubImpl.scala:15)
	at org.jetbrains.plugins.scala.lang.psi.stubs.impl.ScTypeElementOwnerStub.typeElement(ScTypeElementOwnerStub.scala:24)
	at org.jetbrains.plugins.scala.lang.psi.stubs.impl.ScTypeElementOwnerStub.typeElement$(ScTypeElementOwnerStub.scala:18)
	at org.jetbrains.plugins.scala.lang.psi.stubs.impl.ScTypeAliasStubImpl.typeElement(ScTypeAliasStubImpl.scala:15)
	at org.jetbrains.plugins.scala.lang.psi.impl.statements.ScTypeAliasDefinitionImpl.$anonfun$aliasedTypeElement$2(ScTypeAliasDefinitionImpl.scala:46)
	at org.jetbrains.plugins.scala.lang.psi.impl.ScalaStubBasedElementImpl.byPsiOrStub(ScalaPsiElementImpl.scala:118)
	at org.jetbrains.plugins.scala.lang.psi.impl.statements.ScTypeAliasDefinitionImpl.aliasedTypeElement(ScTypeAliasDefinitionImpl.scala:46)
	at org.jetbrains.plugins.scala.lang.psi.api.statements.ScTypeAliasDefinition.aliasedType(ScTypeAliasDefinition.scala:28)
	at org.jetbrains.plugins.scala.lang.psi.api.statements.ScTypeAliasDefinition.aliasedType$(ScTypeAliasDefinition.scala:26)
	at org.jetbrains.plugins.scala.lang.psi.impl.statements.ScTypeAliasDefinitionImpl.aliasedType(ScTypeAliasDefinitionImpl.scala:27)
	at org.jetbrains.plugins.scala.lang.psi.types.package$ScTypeExt$.extractClassSimple$extension(package.scala:174)
	at org.jetbrains.plugins.scala.lang.psi.types.package$ScTypeExt$.checkSimpleClasses$extension(package.scala:190)
	at org.jetbrains.plugins.scala.lang.psi.types.package$ScTypeExt$.canBeSameClass$extension(package.scala:187)
	at org.jetbrains.plugins.scala.lang.psi.types.api.Equivalence.equivInner(Equivalence.scala:40)
	at org.jetbrains.plugins.scala.lang.psi.types.api.Equivalence.equivInner$(Equivalence.scala:34)
	at org.jetbrains.plugins.scala.lang.psi.types.ScalaTypeSystem.equivInner(ScalaTypeSystem.scala:10)
	at org.jetbrains.plugins.scala.lang.psi.types.package$ScTypeExt$.equiv$extension1(package.scala:38)
	at org.jetbrains.plugins.scala.lang.psi.types.ScParameterizedType.equivInner(ScParameterizedType.scala:118)
	at org.jetbrains.plugins.scala.lang.psi.types.ScalaEquivalence$$anon$1.compute(ScalaEquivalence.scala:77)
	at org.jetbrains.plugins.scala.lang.psi.types.ScalaEquivalence$$anon$1.compute(ScalaEquivalence.scala:16)
	at org.jetbrains.plugins.scala.caches.RecursionManager$RecursionGuard.doPreventingRecursion(RecursionManager.scala:59)
	at org.jetbrains.plugins.scala.lang.psi.types.api.Equivalence.equivInner(Equivalence.scala:65)
	at org.jetbrains.plugins.scala.lang.psi.types.api.Equivalence.equivInner(Equivalence.scala:41)
	at org.jetbrains.plugins.scala.lang.psi.types.api.Equivalence.equivInner$(Equivalence.scala:34)
	at org.jetbrains.plugins.scala.lang.psi.types.ScalaTypeSystem.equivInner(ScalaTypeSystem.scala:10)
	at org.jetbrains.plugins.scala.lang.psi.types.package$ScTypeExt$.equiv$extension1(package.scala:38)
	at org.jetbrains.plugins.scala.lang.psi.types.ScalaConformance$LeftConformanceVisitor.checkEquiv(ScalaConformance.scala:282)
	at org.jetbrains.plugins.scala.lang.psi.types.ScalaConformance$LeftConformanceVisitor.visitParameterizedType(ScalaConformance.scala:840)
	at org.jetbrains.plugins.scala.lang.psi.types.ScParameterizedType.visitType(ScParameterizedType.scala:130)
	at org.jetbrains.plugins.scala.lang.psi.types.ScalaConformance$$anon$60.compute(ScalaConformance.scala:40)
	at org.jetbrains.plugins.scala.lang.psi.types.ScalaConformance$$anon$60.compute(ScalaConformance.scala:35)
	at org.jetbrains.plugins.scala.caches.RecursionManager$RecursionGuard.doPreventingRecursion(RecursionManager.scala:59)
	at org.jetbrains.plugins.scala.lang.psi.types.api.Conformance.conformsInner(Conformance.scala:50)
	at org.jetbrains.plugins.scala.lang.psi.types.api.Conformance.conformsInner(Conformance.scala:36)
	at org.jetbrains.plugins.scala.lang.psi.types.api.Conformance.conformsInner$(Conformance.scala:28)
	at org.jetbrains.plugins.scala.lang.psi.types.ScalaTypeSystem.conformsInner(ScalaTypeSystem.scala:10)
	at org.jetbrains.plugins.scala.lang.psi.types.ScalaConformance$$anon$60.compute(ScalaConformance.scala:63)
	at org.jetbrains.plugins.scala.lang.psi.types.ScalaConformance$$anon$60.compute(ScalaConformance.scala:35)
	at org.jetbrains.plugins.scala.caches.RecursionManager$RecursionGuard.doPreventingRecursion(RecursionManager.scala:59)
	at org.jetbrains.plugins.scala.lang.psi.types.api.Conformance.conformsInner(Conformance.scala:50)
	at org.jetbrains.plugins.scala.lang.psi.types.api.Conformance.conformsInner(Conformance.scala:36)
	at org.jetbrains.plugins.scala.lang.psi.types.api.Conformance.conformsInner$(Conformance.scala:28)
	at org.jetbrains.plugins.scala.lang.psi.types.ScalaTypeSystem.conformsInner(ScalaTypeSystem.scala:10)
	at org.jetbrains.plugins.scala.lang.psi.types.package$ScTypeExt$.conforms$extension0(package.scala:42)
	at org.jetbrains.plugins.scala.lang.psi.implicits.ImplicitCollector.checkFunctionByType(ImplicitCollector.scala:575)
	at org.jetbrains.plugins.scala.lang.psi.implicits.ImplicitCollector.checkCompatible(ImplicitCollector.scala:291)
	at org.jetbrains.plugins.scala.lang.psi.implicits.ImplicitCollector.collectCompatibleCandidates(ImplicitCollector.scala:305)
	at org.jetbrains.plugins.scala.lang.psi.implicits.ImplicitCollector.compatible(ImplicitCollector.scala:189)
	at org.jetbrains.plugins.scala.lang.psi.implicits.ImplicitCollector.calc$1(ImplicitCollector.scala:151)
	at org.jetbrains.plugins.scala.lang.psi.implicits.ImplicitCollector.collect(ImplicitCollector.scala:171)
	at org.jetbrains.plugins.scala.lang.psi.api.InferUtil$.findImplicits(InferUtil.scala:173)
	at org.jetbrains.plugins.scala.lang.psi.api.InferUtil$.updateTypeWithImplicitParameters(InferUtil.scala:144)
	at org.jetbrains.plugins.scala.lang.psi.api.expr.ScExpression$Ext$.updatedWithImplicitParameters$extension(ScExpression.scala:324)
	at org.jetbrains.plugins.scala.lang.psi.impl.expr.MethodInvocationImpl.updateImplicitParameters$1(MethodInvocationImpl.scala:76)
	at org.jetbrains.plugins.scala.lang.psi.impl.expr.MethodInvocationImpl.tryToGetInnerTypeExt(MethodInvocationImpl.scala:95)
	at org.jetbrains.plugins.scala.lang.psi.impl.expr.MethodInvocationImpl.innerTypeExt$$cachedFun$1(MethodInvocationImpl.scala:67)
	at org.jetbrains.plugins.scala.lang.psi.impl.expr.MethodInvocationImpl.innerTypeExt(MethodInvocationImpl.scala:65)
	at org.jetbrains.plugins.scala.lang.psi.impl.expr.MethodInvocationImpl.innerType(MethodInvocationImpl.scala:34)
	at org.jetbrains.plugins.scala.lang.psi.api.expr.ScExpression$Ext$.getNonValueType$extension(ScExpression.scala:194)
	at org.jetbrains.plugins.scala.lang.psi.api.expr.ScExpression$Ext$.getTypeWithoutImplicits$extension(ScExpression.scala:286)
	at org.jetbrains.plugins.scala.lang.psi.api.expr.ScExpression$Ext$.getTypeAfterImplicitConversion$extension(ScExpression.scala:230)
	at org.jetbrains.plugins.scala.lang.psi.api.expr.ScExpression.type(ScExpression.scala:71)
	at org.jetbrains.plugins.scala.lang.psi.api.expr.ScExpression.type$(ScExpression.scala:70)
	at org.jetbrains.plugins.scala.lang.psi.impl.expr.ScExpressionImplBase.type(ScExpressionImplBase.scala:11)
	at org.jetbrains.plugins.scala.lang.psi.impl.statements.ScFunctionDefinitionImpl$.org$jetbrains$plugins$scala$lang$psi$impl$statements$ScFunctionDefinitionImpl$$returnTypeInner(ScFunctionDefinitionImpl.scala:111)
	at org.jetbrains.plugins.scala.lang.psi.impl.statements.ScFunctionDefinitionImpl.returnType(ScFunctionDefinitionImpl.scala:72)
	at org.jetbrains.plugins.scala.lang.resolve.MethodTypeProvider$ScFunctionProvider.$anonfun$methodType$3(MethodTypeProvider.scala:114)
	at scala.Option.getOrElse(Option.scala:121)
	at org.jetbrains.plugins.scala.lang.resolve.MethodTypeProvider$ScFunctionProvider.methodType(MethodTypeProvider.scala:114)
	at org.jetbrains.plugins.scala.lang.resolve.MethodTypeProvider.polymorphicType(MethodTypeProvider.scala:43)
	at org.jetbrains.plugins.scala.lang.resolve.MethodTypeProvider.polymorphicType$(MethodTypeProvider.scala:38)
	at org.jetbrains.plugins.scala.lang.resolve.MethodTypeProvider$ScFunctionProvider.polymorphicType(MethodTypeProvider.scala:103)
	at org.jetbrains.plugins.scala.lang.psi.impl.expr.ScReferenceExpressionImpl.convertBindToType(ScReferenceExpressionImpl.scala:362)
	at org.jetbrains.plugins.scala.lang.psi.impl.expr.ScReferenceExpressionImpl.innerType(ScReferenceExpressionImpl.scala:177)
	at org.jetbrains.plugins.scala.lang.psi.api.expr.ScExpression$Ext$.getNonValueType$extension(ScExpression.scala:194)
	at org.jetbrains.plugins.scala.lang.psi.api.expr.ScExpression$Ext$.getTypeWithoutImplicits$extension(ScExpression.scala:286)
	at org.jetbrains.plugins.scala.lang.psi.api.expr.ScExpression$Ext$.getTypeAfterImplicitConversion$extension(ScExpression.scala:230)
	at org.jetbrains.plugins.scala.lang.psi.api.expr.ScExpression.type(ScExpression.scala:71)
	at org.jetbrains.plugins.scala.lang.psi.api.expr.ScExpression.type$(ScExpression.scala:70)
	at org.jetbrains.plugins.scala.lang.psi.impl.expr.ScReferenceExpressionImpl.type(ScReferenceExpressionImpl.scala:45)
	at org.jetbrains.plugins.scala.lang.psi.impl.expr.ScTupleImpl.$anonfun$innerType$1(ScTupleImpl.scala:20)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:233)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:37)
	at scala.collection.TraversableLike.map(TraversableLike.scala:233)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:226)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.jetbrains.plugins.scala.lang.psi.impl.expr.ScTupleImpl.innerType(ScTupleImpl.scala:20)
	at org.jetbrains.plugins.scala.lang.psi.api.expr.ScExpression$Ext$.getNonValueType$extension(ScExpression.scala:194)
	at org.jetbrains.plugins.scala.lang.psi.api.expr.ScExpression$Ext$.getTypeWithoutImplicits$extension(ScExpression.scala:286)
	at org.jetbrains.plugins.scala.lang.psi.api.expr.ScExpression$Ext$.getTypeAfterImplicitConversion$extension(ScExpression.scala:230)
	at org.jetbrains.plugins.scala.lang.psi.types.Compatibility$Expression.getTypeAfterImplicitConversion(Compatibility.scala:87)
	at org.jetbrains.plugins.scala.lang.psi.types.Compatibility$.doNoNamed$1(Compatibility.scala:218)
	at org.jetbrains.plugins.scala.lang.psi.types.Compatibility$.checkConformanceExt(Compatibility.scala:325)
	at org.jetbrains.plugins.scala.lang.psi.types.Compatibility$.checkParameterListConformance$1(Compatibility.scala:413)
	at org.jetbrains.plugins.scala.lang.psi.types.Compatibility$.compatible(Compatibility.scala:443)
	at org.jetbrains.plugins.scala.lang.resolve.processor.MethodResolveProcessor$.problemsFor(MethodResolveProcessor.scala:395)
	at org.jetbrains.plugins.scala.lang.resolve.processor.MethodResolveProcessor$.mapper$1(MethodResolveProcessor.scala:570)
	at org.jetbrains.plugins.scala.lang.resolve.processor.MethodResolveProcessor$.candidates(MethodResolveProcessor.scala:584)
	at org.jetbrains.plugins.scala.lang.resolve.processor.MethodResolveProcessor.collectCandidates(MethodResolveProcessor.scala:166)
	at org.jetbrains.plugins.scala.lang.resolve.processor.MethodResolveProcessor.candidatesS(MethodResolveProcessor.scala:140)
	at org.jetbrains.plugins.scala.lang.resolve.ReferenceExpressionResolver$$anon$1.candidatesS(ReferenceExpressionResolver.scala:149)
	at org.jetbrains.plugins.scala.lang.resolve.processor.BaseProcessor.candidates(BaseProcessor.scala:79)
	at org.jetbrains.plugins.scala.lang.resolve.ReferenceExpressionResolver.smartResolve$1(ReferenceExpressionResolver.scala:154)
	at org.jetbrains.plugins.scala.lang.resolve.ReferenceExpressionResolver.resolveWithName(ReferenceExpressionResolver.scala:196)
	at org.jetbrains.plugins.scala.lang.resolve.ReferenceExpressionResolver.$anonfun$resolve$1(ReferenceExpressionResolver.scala:105)
	at org.jetbrains.plugins.scala.lang.resolve.ReferenceExpressionResolver.resolve(ReferenceExpressionResolver.scala:122)
	at org.jetbrains.plugins.scala.lang.psi.impl.expr.ScReferenceExpressionImpl.multiResolveImpl(ScReferenceExpressionImpl.scala:547)
	at org.jetbrains.plugins.scala.lang.psi.impl.expr.ScReferenceExpressionImpl.$anonfun$multiResolveScala$1(ScReferenceExpressionImpl.scala:64)
	at scala.Option.fold(Option.scala:158)
	at org.jetbrains.plugins.scala.lang.psi.impl.expr.ScReferenceExpressionImpl.multiResolveScala(ScReferenceExpressionImpl.scala:65)
	at org.jetbrains.plugins.scala.lang.psi.impl.expr.ScReferenceImpl.bind(ScReferenceImpl.scala:47)
	at org.jetbrains.plugins.scala.lang.psi.impl.expr.ScReferenceImpl.resolve(ScReferenceImpl.scala:22)
	at org.jetbrains.plugins.scala.injection.ScalaLanguageInjector$.$anonfun$parameterOf$1(ScalaLanguageInjector.scala:415)
	at scala.Option.flatMap(Option.scala:171)
	at org.jetbrains.plugins.scala.injection.ScalaLanguageInjector$.getParameter$1(ScalaLanguageInjector.scala:414)
	at org.jetbrains.plugins.scala.injection.ScalaLanguageInjector$.parameterOf(ScalaLanguageInjector.scala:431)
	at org.jetbrains.plugins.scala.injection.ScalaLanguageInjector$.org$jetbrains$plugins$scala$injection$ScalaLanguageInjector$$annotationOwnerFor(ScalaLanguageInjector.scala:314)
	at org.jetbrains.plugins.scala.injection.ScalaLanguageInjector$.org$jetbrains$plugins$scala$injection$ScalaLanguageInjector$$annotationOwnerForStringLiteral(ScalaLanguageInjector.scala:303)
	at org.jetbrains.plugins.scala.injection.ScalaLanguageInjector.injectUsingAnnotation(ScalaLanguageInjector.scala:202)
	at org.jetbrains.plugins.scala.injection.ScalaLanguageInjector.getLanguagesToInject(ScalaLanguageInjector.scala:67)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageManagerImpl.processInPlaceInjectorsFor(InjectedLanguageManagerImpl.java:421)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.probeElementsUp(InjectedLanguageUtil.java:348)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.enumerate(InjectedLanguageUtil.java:173)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageManagerImpl.enumerateEx(InjectedLanguageManagerImpl.java:315)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryLineMarkersForInjected(LineMarkersPass.java:223)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:185)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectInformation$3(LineMarkersPass.java:96)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:79)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:91)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:55)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:429)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:421)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:397)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:204)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:395)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by romanowski** [comment]
Fixed in 0.22 release.
